"""initial models

Revision ID: bd5ee664f89f
Revises: 
Create Date: 2022-05-25 03:53:12.539111

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "bd5ee664f89f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drones",
        sa.Column(
            "id",
            sqlmodel.sql.sqltypes.GUID(),
            server_default=sa.text("(uuid_generate_v4())"),
            nullable=False,
        ),
        sa.Column(
            "serial_number",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column("model", sa.Integer(), nullable=False),
        sa.Column("weight_limit", sa.Integer(), nullable=False),
        sa.Column("battery_capacity", sa.Float(), nullable=False),
        sa.Column("state", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drones_id"), "drones", ["id"], unique=False)
    op.create_index(
        op.f("ix_drones_serial_number"), "drones", ["serial_number"], unique=False
    )
    op.create_table(
        "medications",
        sa.Column(
            "id",
            sqlmodel.sql.sqltypes.GUID(),
            server_default=sa.text("(uuid_generate_v4())"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("drone_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drone_id"],
            ["drones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_medications_code"), "medications", ["code"], unique=False)
    op.create_index(
        op.f("ix_medications_drone_id"), "medications", ["drone_id"], unique=False
    )
    op.create_index(op.f("ix_medications_id"), "medications", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_medications_id"), table_name="medications")
    op.drop_index(op.f("ix_medications_drone_id"), table_name="medications")
    op.drop_index(op.f("ix_medications_code"), table_name="medications")
    op.drop_table("medications")
    op.drop_index(op.f("ix_drones_serial_number"), table_name="drones")
    op.drop_index(op.f("ix_drones_id"), table_name="drones")
    op.drop_table("drones")
    # ### end Alembic commands ###
